---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: jane
  name: jane
  namespace: kube-system

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jane-binding-ns-simple-admin
  # This indicates that only resources in the "kube-system" namespace are authorized to read.
  namespace: kube-system  
subjects:
- kind: ServiceAccount
  name: jane
  namespace: kube-system
roleRef:
  kind: ClusterRole
  # https://github.com/tomoncle/IstioAndKubernetes-install-scripts/blob/master/install/kubernetes/serviceAccount/serviceaccount-default-role.yaml
  name: ns-simple-admin
  apiGroup: rbac.authorization.k8s.io
